AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Alexa share price skill
Resources:
  alexasharepriceskill:
    Type: 'AWS::Serverless::Function'
    Properties:
      Handler: index.handler
      Runtime: nodejs6.10
      CodeUri: .
      Description: Alexa share price skill
      MemorySize: 128
      Timeout: 7
      Role: !<tag:yaml.org,2002:js/undefined> ''
